# base images
FROM ubuntu:latest
  
# RUN command
RUN echo Hello~ It's shell type command.
RUN ["echo","Hello~ It's exec type command."]
RUN ["/bin/bash", "-c","echo 'Hello~ It's /bin/bash execution in shell type command.'"]
